# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/libevent-epoll-of-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/libevent-epoll-of-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/libevent-epoll-of-c/CMakeFiles /root/libevent-epoll-of-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/libevent-epoll-of-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named s_v2

# Build rule for target.
s_v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 s_v2
.PHONY : s_v2

# fast build rule for target.
s_v2/fast:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/build
.PHONY : s_v2/fast

src/get_file_type.o: src/get_file_type.c.o

.PHONY : src/get_file_type.o

# target to build an object file
src/get_file_type.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/get_file_type.c.o
.PHONY : src/get_file_type.c.o

src/get_file_type.i: src/get_file_type.c.i

.PHONY : src/get_file_type.i

# target to preprocess a source file
src/get_file_type.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/get_file_type.c.i
.PHONY : src/get_file_type.c.i

src/get_file_type.s: src/get_file_type.c.s

.PHONY : src/get_file_type.s

# target to generate assembly for a file
src/get_file_type.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/get_file_type.c.s
.PHONY : src/get_file_type.c.s

src/judge_isdir.o: src/judge_isdir.c.o

.PHONY : src/judge_isdir.o

# target to build an object file
src/judge_isdir.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/judge_isdir.c.o
.PHONY : src/judge_isdir.c.o

src/judge_isdir.i: src/judge_isdir.c.i

.PHONY : src/judge_isdir.i

# target to preprocess a source file
src/judge_isdir.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/judge_isdir.c.i
.PHONY : src/judge_isdir.c.i

src/judge_isdir.s: src/judge_isdir.c.s

.PHONY : src/judge_isdir.s

# target to generate assembly for a file
src/judge_isdir.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/judge_isdir.c.s
.PHONY : src/judge_isdir.c.s

src/libev.o: src/libev.c.o

.PHONY : src/libev.o

# target to build an object file
src/libev.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/libev.c.o
.PHONY : src/libev.c.o

src/libev.i: src/libev.c.i

.PHONY : src/libev.i

# target to preprocess a source file
src/libev.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/libev.c.i
.PHONY : src/libev.c.i

src/libev.s: src/libev.c.s

.PHONY : src/libev.s

# target to generate assembly for a file
src/libev.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/libev.c.s
.PHONY : src/libev.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/main.c.s
.PHONY : src/main.c.s

src/send_dir.o: src/send_dir.c.o

.PHONY : src/send_dir.o

# target to build an object file
src/send_dir.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_dir.c.o
.PHONY : src/send_dir.c.o

src/send_dir.i: src/send_dir.c.i

.PHONY : src/send_dir.i

# target to preprocess a source file
src/send_dir.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_dir.c.i
.PHONY : src/send_dir.c.i

src/send_dir.s: src/send_dir.c.s

.PHONY : src/send_dir.s

# target to generate assembly for a file
src/send_dir.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_dir.c.s
.PHONY : src/send_dir.c.s

src/send_file.o: src/send_file.c.o

.PHONY : src/send_file.o

# target to build an object file
src/send_file.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_file.c.o
.PHONY : src/send_file.c.o

src/send_file.i: src/send_file.c.i

.PHONY : src/send_file.i

# target to preprocess a source file
src/send_file.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_file.c.i
.PHONY : src/send_file.c.i

src/send_file.s: src/send_file.c.s

.PHONY : src/send_file.s

# target to generate assembly for a file
src/send_file.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_file.c.s
.PHONY : src/send_file.c.s

src/send_html_head.o: src/send_html_head.c.o

.PHONY : src/send_html_head.o

# target to build an object file
src/send_html_head.c.o:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_html_head.c.o
.PHONY : src/send_html_head.c.o

src/send_html_head.i: src/send_html_head.c.i

.PHONY : src/send_html_head.i

# target to preprocess a source file
src/send_html_head.c.i:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_html_head.c.i
.PHONY : src/send_html_head.c.i

src/send_html_head.s: src/send_html_head.c.s

.PHONY : src/send_html_head.s

# target to generate assembly for a file
src/send_html_head.c.s:
	$(MAKE) -f CMakeFiles/s_v2.dir/build.make CMakeFiles/s_v2.dir/src/send_html_head.c.s
.PHONY : src/send_html_head.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... s_v2"
	@echo "... edit_cache"
	@echo "... src/get_file_type.o"
	@echo "... src/get_file_type.i"
	@echo "... src/get_file_type.s"
	@echo "... src/judge_isdir.o"
	@echo "... src/judge_isdir.i"
	@echo "... src/judge_isdir.s"
	@echo "... src/libev.o"
	@echo "... src/libev.i"
	@echo "... src/libev.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/send_dir.o"
	@echo "... src/send_dir.i"
	@echo "... src/send_dir.s"
	@echo "... src/send_file.o"
	@echo "... src/send_file.i"
	@echo "... src/send_file.s"
	@echo "... src/send_html_head.o"
	@echo "... src/send_html_head.i"
	@echo "... src/send_html_head.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

